/* Generated by AN DISI Unibo */ 
package it.unibo.swag2pa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Swag2pa extends QActorMsgQueue{
	public MsgHandle_Swag2pa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
