/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureagent;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractTemperatureagent extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractTemperatureagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/temperatureagent/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/temperatureagent/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("checkTemperature",checkTemperature);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "temperatureagent tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"temperatureAgent start\"";
	    	println( temporaryStr );  
	    	//switchTo checkTemperature
	        switchToPlanAsNextState(pr, myselfName, "temperatureagent_"+myselfName, 
	              "checkTemperature",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun checkTemperature = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_checkTemperature",0);
	     pr.incNumIter(); 	
	    	String myselfName = "checkTemperature";  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(5000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "checkTemperature";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = "\"temperatureAgent checking temperature\"";
	    	println( temporaryStr );  
	    	it.unibo.finalTask2018.adapter.temperatureAdapter.getTemperature( myself  );
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " ??currentTemp(T)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "temperature(T)","temperature(T)", guardVars ).toString();
	    	emit( "temperature", temporaryStr );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"temperatureagent_"+myselfName,true,false);
	    }catch(Exception e_checkTemperature){  
	    	 println( getName() + " plan=checkTemperature WARNING:" + e_checkTemperature.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//checkTemperature
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
