/* Generated by AN DISI Unibo */ 
package it.unibo.ledagent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledagent extends QActorMsgQueue{
	public MsgHandle_Ledagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
