/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureagentpa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Temperatureagentpa extends QActorMsgQueue{
	public MsgHandle_Temperatureagentpa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
