/* Generated by AN DISI Unibo */ 
package it.unibo.robotddr1;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robotddr1 extends QActorMsgQueue{
	public MsgHandle_Robotddr1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
