/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSwag2;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhswag2pa extends AbstractEvhswag2pa { 
	public Evhswag2pa(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
