/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSwag2;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evswag extends AbstractEvswag { 
	public Evswag(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
