/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.swag2pa;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Swag2pa extends AbstractSwag2pa { 
	public Swag2pa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
