/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSwag1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhswag1 extends AbstractEvhswag1 { 
	public Evhswag1(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
