/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.humanoperatorra;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Humanoperatorra extends AbstractHumanoperatorra { 
	public Humanoperatorra(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
