/* Generated by AN DISI Unibo */ 
package it.unibo.nrtlogger;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Nrtlogger extends QActorMsgQueue{
	public MsgHandle_Nrtlogger(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
