/* Generated by AN DISI Unibo */ 
package it.unibo.ctxReqAnalysis;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhralogger extends AbstractEvhralogger { 
	public Evhralogger(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
