/* Generated by AN DISI Unibo */ 
package it.unibo.ctxReqAnalysis;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxReqAnalysis  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxreqanalysis", "./srcMore/it/unibo/ctxReqAnalysis/finaltask2018.pl", 
		"./srcMore/it/unibo/ctxReqAnalysis/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
