/* Generated by AN DISI Unibo */ 
package it.unibo.ctxSwag4;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhswag4 extends AbstractEvhswag4 { 
	public Evhswag4(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
