/* Generated by AN DISI Unibo */ 
package it.unibo.ctxVirtualRobotNode;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxVirtualRobotNode  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxvirtualrobotnode", "./srcMore/it/unibo/ctxVirtualRobotNode/finaltask2018.pl", 
		"./srcMore/it/unibo/ctxVirtualRobotNode/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
