/* Generated by AN DISI Unibo */ 
package it.unibo.ctxAppl;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxAppl  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxAppl";
	return QActorContext.initQActorSystem(
		"ctxappl", "./srcMore/it/unibo/ctxAppl/finaltask2018.pl", 
		"./srcMore/it/unibo/ctxAppl/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
