/* Generated by AN DISI Unibo */ 
package it.unibo.clockagentold;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Clockagentold extends QActorMsgQueue{
	public MsgHandle_Clockagentold(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
