/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.virtualenv1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Virtualenv1 extends AbstractVirtualenv1 { 
	public Virtualenv1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
