/* Generated by AN DISI Unibo */ 
package it.unibo.ctxApplPA;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evled extends AbstractEvled { 
	public Evled(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
