/* Generated by AN DISI Unibo */ 
package it.unibo.huelampagentpa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Huelampagentpa extends QActorMsgQueue{
	public MsgHandle_Huelampagentpa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
