/* Generated by AN DISI Unibo */ 
package it.unibo.robotmock;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robotmock extends QActorMsgQueue{
	public MsgHandle_Robotmock(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
