/* Generated by AN DISI Unibo */ 
package it.unibo.mvcCtx;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainMvcCtx  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/mvcCtx";
	return QActorContext.initQActorSystem(
		"mvcctx", "./srcMore/it/unibo/mvcCtx/mvc.pl", 
		"./srcMore/it/unibo/mvcCtx/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
