/* Generated by AN DISI Unibo */ 
package it.unibo.rrrlogger;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Rrrlogger extends QActorMsgQueue{
	public MsgHandle_Rrrlogger(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
