/* Generated by AN DISI Unibo */ 
package it.unibo.swag4;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractSwag4 extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractSwag4(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/swag4/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/swag4/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("cleaning",cleaning);
	    	stateTab.put("handleFront",handleFront);
	    	stateTab.put("avoidMobile",avoidMobile);
	    	stateTab.put("avoidFix",avoidFix);
	    	stateTab.put("checkDoor",checkDoor);
	    	stateTab.put("doorFound",doorFound);
	    	stateTab.put("goToPrevLevel",goToPrevLevel);
	    	stateTab.put("resumeLastPosition",resumeLastPosition);
	    	stateTab.put("failure",failure);
	    	stateTab.put("giveUp",giveUp);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "swag4 tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"swag4 start\"";
	    	println( temporaryStr );  
	    	parg = "consult(\"./swagtest.pl\")";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//switchTo cleaning
	        switchToPlanAsNextState(pr, myselfName, "swag4_"+myselfName, 
	              "cleaning",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun cleaning = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("cleaning",-1);
	    	String myselfName = "cleaning";  
	    	temporaryStr = "\"cleaning\"";
	    	println( temporaryStr );  
	    	parg = "addState(cleaning)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,w(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleFront") }, 
	          new String[]{"true","E","frontSonar" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_cleaning){  
	    	 println( getName() + " plan=cleaning WARNING:" + e_cleaning.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//cleaning
	    
	    StateFun handleFront = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleFront",-1);
	    	String myselfName = "handleFront";  
	    	temporaryStr = "\"handleFront\"";
	    	println( temporaryStr );  
	    	parg = "addState(handleFront)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,h(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	temporaryStr = "\"possible mobile obstacle\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleFront";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,w(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	temporaryStr = "\"provo ad avanzare\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("avoidFix") }, 
	          new String[]{"true","E","frontSonar" },
	          800, "avoidMobile" );//msgTransition
	    }catch(Exception e_handleFront){  
	    	 println( getName() + " plan=handleFront WARNING:" + e_handleFront.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleFront
	    
	    StateFun avoidMobile = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("avoidMobile",-1);
	    	String myselfName = "avoidMobile";  
	    	temporaryStr = "\"avoidMobile\"";
	    	println( temporaryStr );  
	    	parg = "addState(avoidMobile)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = "\"ok, ostacolo superato\"";
	    	println( temporaryStr );  
	    	//switchTo cleaning
	        switchToPlanAsNextState(pr, myselfName, "swag4_"+myselfName, 
	              "cleaning",false, false, null); 
	    }catch(Exception e_avoidMobile){  
	    	 println( getName() + " plan=avoidMobile WARNING:" + e_avoidMobile.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//avoidMobile
	    
	    StateFun avoidFix = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("avoidFix",-1);
	    	String myselfName = "avoidFix";  
	    	temporaryStr = "\"avoidFix\"";
	    	println( temporaryStr );  
	    	parg = "addState(avoidFix)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,h(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?exploring(DIR)" )) != null ){
	    	temporaryStr = "exploring(DIR)";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	else{ temporaryStr = "exploring(r)";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	addRule( temporaryStr );  
	    	}parg = "avoidFixTry";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?avoidFixGiveUp" )) != null ){
	    	{//actionseq
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?exploring(l)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(giveUpLeft)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	}
	    	else{ temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(giveUpRight)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	}parg = "switchExplorationDir";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = "\"Raggiunti max tentativi\"";
	    	println( temporaryStr );  
	    	};//actionseq
	    	}
	    	else{ {//actionseq
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "avoidFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = "\"proviamo a girarci intorno\"";
	    	println( temporaryStr );  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?exploring(l)" )) != null ){
	    	{//actionseq
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,a(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	temporaryStr = "\"da sinistra\"";
	    	println( temporaryStr );  
	    	};//actionseq
	    	}
	    	else{ {//actionseq
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,d(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	temporaryStr = "\"da destra\"";
	    	println( temporaryStr );  
	    	};//actionseq
	    	}//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "avoidFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,w(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(600,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "avoidFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,h(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "avoidFix";
	    	if( ! aar.getGoon() ) return ;
	    	};//actionseq
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("failure"), stateTab.get("giveUp") }, 
	          new String[]{"true","E","frontSonar", "true","M","swagmsg" },
	          800, "checkDoor" );//msgTransition
	    }catch(Exception e_avoidFix){  
	    	 println( getName() + " plan=avoidFix WARNING:" + e_avoidFix.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//avoidFix
	    
	    StateFun checkDoor = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("checkDoor",-1);
	    	String myselfName = "checkDoor";  
	    	temporaryStr = "\"checkDoor\"";
	    	println( temporaryStr );  
	    	parg = "addState(checkDoor)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?exploring(r)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,a(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}
	    	else{ temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,d(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "checkDoor";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,w(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(400,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "checkDoor";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,h(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "checkDoor";
	    	if( ! aar.getGoon() ) return ;
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("avoidFix") }, 
	          new String[]{"true","E","frontSonar" },
	          800, "doorFound" );//msgTransition
	    }catch(Exception e_checkDoor){  
	    	 println( getName() + " plan=checkDoor WARNING:" + e_checkDoor.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//checkDoor
	    
	    StateFun doorFound = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doorFound",-1);
	    	String myselfName = "doorFound";  
	    	temporaryStr = "\"doorFound\"";
	    	println( temporaryStr );  
	    	parg = "addState(doorFound)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,w(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "doorFound";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,h(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?exploring(r)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,a(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}
	    	else{ temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,d(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}
	    	//switchTo goToPrevLevel
	        switchToPlanAsNextState(pr, myselfName, "swag4_"+myselfName, 
	              "goToPrevLevel",false, false, null); 
	    }catch(Exception e_doorFound){  
	    	 println( getName() + " plan=doorFound WARNING:" + e_doorFound.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doorFound
	    
	    StateFun goToPrevLevel = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("goToPrevLevel",-1);
	    	String myselfName = "goToPrevLevel";  
	    	temporaryStr = "\"goToPrevLevel\"";
	    	println( temporaryStr );  
	    	parg = "addState(goToPrevLevel)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "goToPrevLevel";
	    	if( ! aar.getGoon() ) return ;
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?counter(foundFix,C)" )) != null ){
	    	{//actionseq
	    	parg = "decremFoundFix";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,w(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "goToPrevLevel";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,h(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	};//actionseq
	    	}
	    	else{ {//actionseq
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(initialP)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?exploring(r)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,d(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}
	    	else{ temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,a(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "goToPrevLevel";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = "\"riprendo la direzione di marcia\"";
	    	println( temporaryStr );  
	    	};//actionseq
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("cleaning") }, 
	          new String[]{"true","M","swagmsg" },
	          300, "goToPrevLevel" );//msgTransition
	    }catch(Exception e_goToPrevLevel){  
	    	 println( getName() + " plan=goToPrevLevel WARNING:" + e_goToPrevLevel.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//goToPrevLevel
	    
	    StateFun resumeLastPosition = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("resumeLastPosition",-1);
	    	String myselfName = "resumeLastPosition";  
	    	temporaryStr = "\"resumeLastPosition\"";
	    	println( temporaryStr );  
	    	parg = "addState(resumeLastPosition)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "resumeLastPosition";
	    	if( ! aar.getGoon() ) return ;
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?counter(foundFix,C)" )) != null ){
	    	{//actionseq
	    	parg = "decremFoundFix";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,w(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "resumeLastPosition";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,h(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "resumeLastPosition";
	    	if( ! aar.getGoon() ) return ;
	    	};//actionseq
	    	}
	    	else{ {//actionseq
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(initialP)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,d(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	temporaryStr = "\"fronteggio l'invalicabile muro\"";
	    	println( temporaryStr );  
	    	};//actionseq
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("avoidFix") }, 
	          new String[]{"true","M","swagmsg" },
	          800, "resumeLastPosition" );//msgTransition
	    }catch(Exception e_resumeLastPosition){  
	    	 println( getName() + " plan=resumeLastPosition WARNING:" + e_resumeLastPosition.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//resumeLastPosition
	    
	    StateFun failure = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("failure",-1);
	    	String myselfName = "failure";  
	    	temporaryStr = "\"failure\"";
	    	println( temporaryStr );  
	    	parg = "addState(failure)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?exploring(r)" )) != null ){
	    	{//actionseq
	    	temporaryStr = "\"failure da destra\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(giveUpRight)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "failure";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,a(0))", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	};//actionseq
	    	}
	    	else{ {//actionseq
	    	temporaryStr = "\"failure da sinistra\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(giveUpLeft)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	};//actionseq
	    	}parg = "switchExplorationDir";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("giveUp") }, 
	          new String[]{"true","M","swagmsg" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_failure){  
	    	 println( getName() + " plan=failure WARNING:" + e_failure.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//failure
	    
	    StateFun giveUp = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("giveUp",-1);
	    	String myselfName = "giveUp";  
	    	temporaryStr = "\"giveUp\"";
	    	println( temporaryStr );  
	    	parg = "addState(giveUp)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	parg = "decremFoundFix";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(giveUpRight)");
	    	if( currentMessage != null && currentMessage.msgId().equals("swagmsg") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = "\"giveUpRight\"";
	    		println( temporaryStr );  
	    		//delay  ( no more reactive within a plan)
	    		aar = delayReactive(800,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "giveUp";
	    		if( ! aar.getGoon() ) return ;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CATEG,NAME,CMD)","ctrlEvent(robot,r1,a(0))", guardVars ).toString();
	    		emit( "ctrlEvent", temporaryStr );
	    		//delay  ( no more reactive within a plan)
	    		aar = delayReactive(800,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "giveUp";
	    		if( ! aar.getGoon() ) return ;
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(resumeLastPos)", guardVars ).toString();
	    		sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(giveUpLeft)");
	    	if( currentMessage != null && currentMessage.msgId().equals("swagmsg") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = "\"giveUpLeft\"";
	    		println( temporaryStr );  
	    		temporaryStr = "foundFix(X)";
	    		removeRule( temporaryStr );  
	    		temporaryStr = "exploring(l)";
	    		removeRule( temporaryStr );  
	    		};//actionseq
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"swag4_"+myselfName,false,
	          new StateFun[]{stateTab.get("resumeLastPosition") }, 
	          new String[]{"true","M","swagmsg" },
	          800, "init" );//msgTransition
	    }catch(Exception e_giveUp){  
	    	 println( getName() + " plan=giveUp WARNING:" + e_giveUp.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//giveUp
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
