/* Generated by AN DISI Unibo */ 
package it.unibo.swag4;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Swag4 extends QActorMsgQueue{
	public MsgHandle_Swag4(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
