/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureagentold;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Temperatureagentold extends QActorMsgQueue{
	public MsgHandle_Temperatureagentold(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
