/* Generated by AN DISI Unibo */ 
package it.unibo.testerrobot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testerrobot extends QActorMsgQueue{
	public MsgHandle_Testerrobot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
