/* Generated by AN DISI Unibo */ 
package it.unibo.ctxVirtualRobotNode;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhnodebroker extends AbstractEvhnodebroker { 
	public Evhnodebroker(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
