/* Generated by AN DISI Unibo */ 
package it.unibo.huelampagentra;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Huelampagentra extends QActorMsgQueue{
	public MsgHandle_Huelampagentra(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
