/* Generated by AN DISI Unibo */ 
package it.unibo.fetester;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Fetester extends QActorMsgQueue{
	public MsgHandle_Fetester(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
