/* Generated by AN DISI Unibo */ 
package it.unibo.nodeenv;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Nodeenv extends QActorMsgQueue{
	public MsgHandle_Nodeenv(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
