/* Generated by AN DISI Unibo */ 
package it.unibo.huelampagentgui;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Huelampagentgui extends QActorMsgQueue{
	public MsgHandle_Huelampagentgui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
