/* Generated by AN DISI Unibo */ 
package it.unibo.raintegratorqa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Raintegratorqa extends QActorMsgQueue{
	public MsgHandle_Raintegratorqa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
