/* Generated by AN DISI Unibo */ 
package it.unibo.testerenv;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testerenv extends QActorMsgQueue{
	public MsgHandle_Testerenv(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
