/* Generated by AN DISI Unibo */ 
package it.unibo.realrobottest;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Realrobottest extends QActorMsgQueue{
	public MsgHandle_Realrobottest(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
