/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureagentra;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Temperatureagentra extends QActorMsgQueue{
	public MsgHandle_Temperatureagentra(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
