/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.swag4;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Swag4 extends AbstractSwag4 { 
	public Swag4(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
