/* Generated by AN DISI Unibo */ 
package it.unibo.clockagentra;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Clockagentra extends QActorMsgQueue{
	public MsgHandle_Clockagentra(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
