/* Generated by AN DISI Unibo */ 
package it.unibo.testertime;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testertime extends QActorMsgQueue{
	public MsgHandle_Testertime(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
