/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotDDR;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRobotDDR  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxrobotddr", "./srcMore/it/unibo/ctxRobotDDR/finaltask2018.pl", 
		"./srcMore/it/unibo/ctxRobotDDR/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
