/* Generated by AN DISI Unibo */ 
package it.unibo.ctxHueLampAgent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxHueLampAgent  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxhuelampagent", "./srcMore/it/unibo/ctxHueLampAgent/finaltask2018.pl", 
		"./srcMore/it/unibo/ctxHueLampAgent/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
