/* Generated by AN DISI Unibo */ 
package it.unibo.ctx;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhtml extends AbstractEvhtml { 
	public Evhtml(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
