/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.temperatureagentra;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Temperatureagentra extends AbstractTemperatureagentra { 
	public Temperatureagentra(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
