/* Generated by AN DISI Unibo */ 
package it.unibo.ddrlogger;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ddrlogger extends QActorMsgQueue{
	public MsgHandle_Ddrlogger(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
