/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.temperatureagent1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Temperatureagent1 extends AbstractTemperatureagent1 { 
	public Temperatureagent1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
