/* Generated by AN DISI Unibo */ 
package it.unibo.swag1;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractSwag1 extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractSwag1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/swag1/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/swag1/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("receivedCmd",receivedCmd);
	    	stateTab.put("detectedBySonar",detectedBySonar);
	    	stateTab.put("cleaning",cleaning);
	    	stateTab.put("detectedByFinal",detectedByFinal);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "swag1 tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_init",0);
	     pr.incNumIter(); 	
	    	String myselfName = "init";  
	    	temporaryStr = "\"swag start\"";
	    	println( temporaryStr );  
	    	parg = "setCurrentState(init)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(CMD)");
	    	if( currentMessage != null && currentMessage.msgId().equals("swagmsg") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="logmsg(swagmsg,cmd(CMD))";
	    		/* AddRule */
	    		parg = updateVars(Term.createTerm("cmd(CMD)"),  Term.createTerm("cmd(CMD)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) addRule(parg);	    		  					
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"swag1_"+myselfName,false,
	          new StateFun[]{stateTab.get("receivedCmd") }, 
	          new String[]{"true","M","externalcmd" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun receivedCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("receivedCmd",-1);
	    	String myselfName = "receivedCmd";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(CMD)");
	    	if( currentMessage != null && currentMessage.msgId().equals("externalcmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="logmsg(externalcmd,usercmd(CMD))";
	    		/* AddRule */
	    		parg = updateVars(Term.createTerm("usercmd(CMD)"),  Term.createTerm("usercmd(CMD)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) addRule(parg);	    		  					
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(clean)");
	    	if( currentMessage != null && currentMessage.msgId().equals("externalcmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = "\"ricevuto clean\"";
	    		println( temporaryStr );  
	    		temporaryStr = "startCmd";
	    		addRule( temporaryStr );  
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(halt)");
	    	if( currentMessage != null && currentMessage.msgId().equals("externalcmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg = "\"ricevuto halt\"";
	    		/* Print */
	    		parg =  updateVars( Term.createTerm("usercmd(CMD)"), 
	    		                    Term.createTerm("usercmd(halt)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) println( parg );
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"swag1_"+myselfName,false,
	          new StateFun[]{stateTab.get("detectedBySonar") }, 
	          new String[]{" ??startCmd" ,"E","sonarSensor" },
	          800, "init" );//msgTransition
	    }catch(Exception e_receivedCmd){  
	    	 println( getName() + " plan=receivedCmd WARNING:" + e_receivedCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//receivedCmd
	    
	    StateFun detectedBySonar = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("detectedBySonar",-1);
	    	String myselfName = "detectedBySonar";  
	    	temporaryStr = "\"detected by a sonar\"";
	    	println( temporaryStr );  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sonar(sonar1,D)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sonarSensor") && 
	    		pengine.unify(curT, Term.createTerm("sonar(NAME,DISTANCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="sonarDetect(sonar1,D)";
	    			/* AddRule */
	    			parg = updateVars(Term.createTerm("sonar(NAME,DISTANCE)"),  Term.createTerm("sonar(sonar1,D)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) addRule(parg);	    		  					
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?isCloseTo(sonar1)" )) != null ){
	    	{//actionseq
	    	temporaryStr = "\"close to sonar1\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(clean)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	};//actionseq
	    	}
	    	else{ temporaryStr = "\"NOT close to sonar1!\"";
	    	println( temporaryStr );  
	    	}temporaryStr = "sonarDetect(sonar1,D)";
	    	removeRule( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"swag1_"+myselfName,false,
	          new StateFun[]{stateTab.get("cleaning") }, 
	          new String[]{"true","M","swagmsg" },
	          800, "init" );//msgTransition
	    }catch(Exception e_detectedBySonar){  
	    	 println( getName() + " plan=detectedBySonar WARNING:" + e_detectedBySonar.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//detectedBySonar
	    
	    StateFun cleaning = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("cleaning",-1);
	    	String myselfName = "cleaning";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("cmd(CMD)");
	    	if( currentMessage != null && currentMessage.msgId().equals("swagmsg") && 
	    		pengine.unify(curT, Term.createTerm("cmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="logmsg(swagmsg,cmd(CMD))";
	    		/* AddRule */
	    		parg = updateVars(Term.createTerm("cmd(CMD)"),  Term.createTerm("cmd(CMD)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) addRule(parg);	    		  					
	    	}
	    	parg = "setCurrentState(cleaning)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = "\"cleaning\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"swag1_"+myselfName,false,
	          new StateFun[]{stateTab.get("detectedByFinal"), stateTab.get("receivedCmd") }, 
	          new String[]{"true","E","sonarSensor", "true","M","externalcmd" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_cleaning){  
	    	 println( getName() + " plan=cleaning WARNING:" + e_cleaning.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//cleaning
	    
	    StateFun detectedByFinal = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("detectedByFinal",-1);
	    	String myselfName = "detectedByFinal";  
	    	temporaryStr = "\"detected by a sonar\"";
	    	println( temporaryStr );  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sonar(sonar2,D)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sonarSensor") && 
	    		pengine.unify(curT, Term.createTerm("sonar(NAME,DISTANCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="sonarDetect(sonar2,D)";
	    			/* AddRule */
	    			parg = updateVars(Term.createTerm("sonar(NAME,DISTANCE)"),  Term.createTerm("sonar(sonar2,D)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) addRule(parg);	    		  					
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?isCloseTo(sonar2)" )) != null ){
	    	{//actionseq
	    	temporaryStr = "\"close to sonar2, end of cleaning\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmd(CMD)","cmd(halt)", guardVars ).toString();
	    	sendMsg("swagmsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	};//actionseq
	    	}
	    	else{ temporaryStr = "\"NOT close to sonar2!\"";
	    	println( temporaryStr );  
	    	}temporaryStr = "sonarDetect(sonar2,D)";
	    	removeRule( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"swag1_"+myselfName,false,
	          new StateFun[]{stateTab.get("init") }, 
	          new String[]{"true","M","swagmsg" },
	          800, "cleaning" );//msgTransition
	    }catch(Exception e_detectedByFinal){  
	    	 println( getName() + " plan=detectedByFinal WARNING:" + e_detectedByFinal.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//detectedByFinal
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
