/* Generated by AN DISI Unibo */ 
package it.unibo.realrobotbroker;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Realrobotbroker extends QActorMsgQueue{
	public MsgHandle_Realrobotbroker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
