/* Generated by AN DISI Unibo */ 
package it.unibo.realrobotrasp;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Realrobotrasp extends QActorMsgQueue{
	public MsgHandle_Realrobotrasp(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
