/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.swag3;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Swag3 extends AbstractSwag3 { 
	public Swag3(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
