/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRealRobotMock;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhrealmockbroker extends AbstractEvhrealmockbroker { 
	public Evhrealmockbroker(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
