/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRealRobotMock;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhrealmock extends AbstractEvhrealmock { 
	public Evhrealmock(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
