/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.clockagent1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Clockagent1 extends AbstractClockagent1 { 
	public Clockagent1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
