/* Generated by AN DISI Unibo */ 
package it.unibo.ctxApplPA;
import alice.tuprolog.Term;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.qactors.platform.EventHandlerComponent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.QActorUtils;

public abstract class AbstractEvhpalogger extends EventHandlerComponent { 
protected IEventItem event;
	public AbstractEvhpalogger(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, eventIds, outEnvView);
  	}
	@Override
	public void doJob() throws Exception {	}
	
	public void handleCurrentEvent() throws Exception {
		event = this.currentEvent; //AKKA getEventItem();
		if( event == null ) return;
		QActorUtils.sendMsgExecInternal("palogger_ctrl","memoCurrentEvent("+event.getPrologRep()+",true)");
		//QActorUtils.getQActor("palogger_ctrl").memoCurrentEvent( event, true);
		QActorUtils.sendMsgExecInternal("palogger_ctrl","dologevent");
		//QActorUtils.solveGoal(QActorUtils.getQActor("palogger_ctrl").getPrologEngine(),"dologevent");
	}//handleCurrentEvent
	
	@Override
	protected void handleQActorEvent(IEventItem ev) {
		super.handleQActorEvent(ev);
 		try {
			handleCurrentEvent();
		} catch (Exception e) {
 			e.printStackTrace();
		}
	}//handleQActorEvent
	
}
