/* Generated by AN DISI Unibo */ 
package it.unibo.applmocktest;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Applmocktest extends QActorMsgQueue{
	public MsgHandle_Applmocktest(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
