/* Generated by AN DISI Unibo */ 
package it.unibo.thermoagentpa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Thermoagentpa extends QActorMsgQueue{
	public MsgHandle_Thermoagentpa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
