/* Generated by AN DISI Unibo */ 
package it.unibo.humanoperatorwithgui;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Humanoperatorwithgui extends QActorMsgQueue{
	public MsgHandle_Humanoperatorwithgui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
