/* Generated by AN DISI Unibo */ 
package it.unibo.ctxClockAgent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxClockAgent  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxclockagent", "./srcMore/it/unibo/ctxClockAgent/finaltask2018.pl", 
		"./srcMore/it/unibo/ctxClockAgent/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
