/* Generated by AN DISI Unibo */ 
package it.unibo.testertemp;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testertemp extends QActorMsgQueue{
	public MsgHandle_Testertemp(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
