/* Generated by AN DISI Unibo */ 
package it.unibo.feactivator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Feactivator extends QActorMsgQueue{
	public MsgHandle_Feactivator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
