/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.humanoperatorqa1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Humanoperatorqa1 extends AbstractHumanoperatorqa1 { 
	public Humanoperatorqa1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
