/* Generated by AN DISI Unibo */ 
package it.unibo.huelampagent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Huelampagent extends QActorMsgQueue{
	public MsgHandle_Huelampagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
