/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.swag1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Swag1 extends AbstractSwag1 { 
	public Swag1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
