/* Generated by AN DISI Unibo */ 
package it.unibo.ctxFrontendActivator;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhfe extends AbstractEvhfe { 
	public Evhfe(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
