/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRealRobotRasp;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhrealbroker extends AbstractEvhrealbroker { 
	public Evhrealbroker(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
