/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.appl1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Appl1 extends AbstractAppl1 { 
	public Appl1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
