/* Generated by AN DISI Unibo */ 
package it.unibo.robotnode;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robotnode extends QActorMsgQueue{
	public MsgHandle_Robotnode(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
