/* Generated by AN DISI Unibo */ 
package it.unibo.humanoperatorqa1;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Humanoperatorqa1 extends QActorMsgQueue{
	public MsgHandle_Humanoperatorqa1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
