/* Generated by AN DISI Unibo */ 
package it.unibo.humanoperatorqa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Humanoperatorqa extends QActorMsgQueue{
	public MsgHandle_Humanoperatorqa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
