/* Generated by AN DISI Unibo */ 
package it.unibo.ddr;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ddr extends QActorMsgQueue{
	public MsgHandle_Ddr(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
