/* Generated by AN DISI Unibo */ 
package it.unibo.ctxDdr;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhddrlogger extends AbstractEvhddrlogger { 
	public Evhddrlogger(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
