/* Generated by AN DISI Unibo */ 
package it.unibo.ctxDdr;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhddr extends AbstractEvhddr { 
	public Evhddr(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
