/* Generated by AN DISI Unibo */ 
package it.unibo.controllerpa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Controllerpa extends QActorMsgQueue{
	public MsgHandle_Controllerpa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
