/* Generated by AN DISI Unibo */ 
package it.unibo.swagpa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Swagpa extends QActorMsgQueue{
	public MsgHandle_Swagpa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
