/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureagent1;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Temperatureagent1 extends QActorMsgQueue{
	public MsgHandle_Temperatureagent1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
