/* Generated by AN DISI Unibo */ 
package it.unibo.clockagent1;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Clockagent1 extends QActorMsgQueue{
	public MsgHandle_Clockagent1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
