/* Generated by AN DISI Unibo */ 
package it.unibo.huelampagentold;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Huelampagentold extends QActorMsgQueue{
	public MsgHandle_Huelampagentold(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
