/* Generated by AN DISI Unibo */ 
package it.unibo.clockagentpa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Clockagentpa extends QActorMsgQueue{
	public MsgHandle_Clockagentpa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
