/* Generated by AN DISI Unibo */ 
package it.unibo.ledrobotmock;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledrobotmock extends QActorMsgQueue{
	public MsgHandle_Ledrobotmock(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
