/* Generated by AN DISI Unibo */ 
package it.unibo.ledraspagent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledraspagent extends QActorMsgQueue{
	public MsgHandle_Ledraspagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
