/* Generated by AN DISI Unibo */ 
package it.unibo.testerrobotnode;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testerrobotnode extends QActorMsgQueue{
	public MsgHandle_Testerrobotnode(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
